abbr ll="exa -lg --time-style long-iso"\ -S --quiet
abbr la="exa -lag --time-style long-iso"\ -S --quiet
abbr lt="exa -l -T"\ -S --quiet
abbr g="git"\ -S --quiet
abbr gb="git branch"\ -S --quiet
abbr gs="git status"\ -S --quiet
abbr gf="git fetch"\ -S --quiet
abbr gc="git checkout"\ -S --quiet
abbr gl="git log"\ -S --quiet
abbr glg="git log --graph"\ -S --quiet
abbr gr="git rebase"\ -S --quiet
abbr gwl="git worktree list"\ -S --quiet
abbr tfp="terraform plan"\ -S --quiet
abbr tff="terraform fmt"\ -S --quiet
abbr tfi="terraform init"\ -S --quiet
abbr tfa="terraform apply"\ -S --quiet
abbr bi="bundle install --path vendor/bundle -j4"\ -S --quiet
abbr rc="bundle ex rails c"\ -S --quiet
abbr gmdelete="git branch --merged|egrep -v \"\*|develop|master\"|xargs git branch -d"\ -S --quiet
abbr k="kubectl"\ -S --quiet
