[tools]
awscli = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
direnv = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
tmux = "3.5a"
usage = "latest"

